# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    docker:
      - image: maven:3.5.2-jdk-8-alpine
    working_directory: /tmp
    steps:
      - checkout
      - run:
          name: "Build Maven Project"
          command: |
            cd tp6/spring-boot/;
            mvn package;
            mkdir artifacts;
            cp tp6/spring-boot/target/*.jar /tmp/artifacts
      - store_artifacts:
          path: /tmp/artifacts
# Invoke jobs via workflows
workflows:
  build-workflow:
    jobs:
      - build
