version: '3.6'
services:
  app:
    build:
      context: ./
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    ports:
      - "5001:5000"
  redis:
    image: redis:3.2-alpine
    volumes:
      - redis_data:/data
volumes:
  redis_data:
